AWSTemplateFormatVersion: "2010-09-09"
Resources:
  LambdaLayer:
    Type: "AWS::Lambda::LayerVersion"
    Properties:
      CompatibleRuntimes:
        - python3.8
#        - python3.9
      Content:
        S3Bucket: !Sub 'layer-${AWS::AccountId}'
        S3Key: lwtools.zip #Layer File
      Description: LINEWORKS Twitter Google SpreadSheet
      LayerName: !Sub "lwtools-layer"
